# Generated by Django 3.1.7 on 2021-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['destination']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='adventure',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='return_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adventure_images'),
        ),
    ]
