# Generated by Django 3.1.7 on 2021-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
