# Generated by Django 3.1.7 on 2021-03-18 23:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_auto_20210318_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=100)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='destination',
        ),
        migrations.AddField(
            model_name='adventure',
            name='adventure_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.adventurelocation'),
        ),
    ]
