# Generated by Django 3.1.7 on 2021-03-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_auto_20210320_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='return_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='adventure',
            old_name='departure_date',
            new_name='start_date',
        ),
    ]
